export const espnBracket = {
  activeRound: 6,
  champ: {
    altClr: "f1f2f3",
    clr: "0c2340",
    logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
    logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png",
    secondaryText: "NCAA Champions",
    season: "2023",
  },
  id: "22",
  isFastcast: false,
  league: "NCAAM",
  leagueId: "41",
  matchups: [
    {
      competitorOne: {
        abbreviation: "AMCC",
        alternateColor: "007f3e",
        color: "0067c5",
        id: "357",
        location: "Texas A&M-Corpus Christi",
        name: "Texas A&M-CC",
        homeAway: "home",
        order: 1,
        score: "75",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/357.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/357.png",
        seed: "16",
      },
      competitorTwo: {
        abbreviation: "SEMO",
        alternateColor: "000000",
        color: "c8102e",
        id: "2546",
        location: "Southeast Missouri State",
        name: "SE Missouri",
        homeAway: "away",
        order: 2,
        score: "71",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2546.png",
        seed: "16",
      },
      date: "2023-03-14T22:40:00Z",
      id: "401522117",
      link: "/mens-college-basketball/game/_/gameId/401522117/se-missouri-texas-am-cc",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 1,
      roundId: 0,
      label: "SOUTH",
      regionId: 1,
    },
    {
      competitorOne: {
        abbreviation: "MSST",
        alternateColor: "c1c6c8",
        color: "5d1725",
        id: "344",
        location: "Mississippi State",
        name: "Mississippi St",
        homeAway: "home",
        order: 1,
        score: "59",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/344.png",
        seed: "11",
      },
      competitorTwo: {
        abbreviation: "PITT",
        alternateColor: "231f20",
        color: "003263",
        id: "221",
        location: "Pittsburgh",
        name: "Pitt",
        homeAway: "away",
        order: 2,
        score: "60",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/221.png",
        seed: "11",
      },
      date: "2023-03-15T01:34:00Z",
      id: "401522116",
      link: "/mens-college-basketball/game/_/gameId/401522116/pitt-mississippi-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 2,
      roundId: 0,
      label: "MIDWEST",
      regionId: 3,
    },
    {
      competitorOne: {
        abbreviation: "ASU",
        alternateColor: "ffc72c",
        color: "8e0c3a",
        id: "9",
        location: "Arizona State",
        name: "Arizona St",
        homeAway: "home",
        order: 1,
        score: "98",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/9.png",
        seed: "11",
      },
      competitorTwo: {
        abbreviation: "NEV",
        alternateColor: "ffffff",
        color: "002d62",
        id: "2440",
        location: "Nevada",
        name: "Nevada",
        homeAway: "away",
        order: 2,
        score: "73",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2440.png",
        seed: "11",
      },
      date: "2023-03-16T01:10:00Z",
      id: "401522119",
      link: "/mens-college-basketball/game/_/gameId/401522119/nevada-arizona-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 3,
      roundId: 0,
      label: "WEST",
      regionId: 4,
    },
    {
      competitorOne: {
        abbreviation: "TXSO",
        alternateColor: "ffffff",
        color: "860038",
        id: "2640",
        location: "Texas Southern",
        name: "Texas Southern",
        homeAway: "home",
        order: 1,
        score: "61",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2640.png",
        seed: "16",
      },
      competitorTwo: {
        abbreviation: "FDU",
        alternateColor: "28334a",
        color: "72293c",
        id: "161",
        location: "Fairleigh Dickinson",
        name: "Fair Dickinson",
        homeAway: "away",
        order: 2,
        score: "84",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/161.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/161.png",
        seed: "16",
      },
      date: "2023-03-15T22:40:00Z",
      id: "401522118",
      link: "/mens-college-basketball/game/_/gameId/401522118/fair-dickinson-texas-southern",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 4,
      roundId: 0,
      label: "EAST",
      regionId: 2,
    },
    {
      competitorOne: {
        abbreviation: "ALA",
        alternateColor: "ffffff",
        color: "9e1632",
        id: "333",
        location: "Alabama",
        name: "Alabama",
        homeAway: "home",
        order: 1,
        score: "96",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/333.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "AMCC",
        alternateColor: "007f3e",
        color: "0067c5",
        id: "357",
        location: "Texas A&M-Corpus Christi",
        name: "Texas A&M-CC",
        homeAway: "away",
        order: 2,
        score: "75",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/357.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/357.png",
        seed: "16",
      },
      date: "2023-03-16T19:15:00Z",
      id: "401522123",
      link: "/mens-college-basketball/game/_/gameId/401522123/texas-am-cc-alabama",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 1,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "MD",
        alternateColor: "ffcd00",
        color: "D5002B",
        id: "120",
        location: "Maryland",
        name: "Maryland",
        homeAway: "home",
        order: 1,
        score: "67",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/120.png",
        seed: "8",
      },
      competitorTwo: {
        abbreviation: "WVU",
        alternateColor: "eaaa00",
        color: "002855",
        id: "277",
        location: "West Virginia",
        name: "West Virginia",
        homeAway: "away",
        order: 2,
        score: "65",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/277.png",
        seed: "9",
      },
      date: "2023-03-16T16:15:00Z",
      id: "401522122",
      link: "/mens-college-basketball/game/_/gameId/401522122/west-virginia-maryland",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 2,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "SDSU",
        alternateColor: "000000",
        color: "c41230",
        id: "21",
        location: "San Diego State",
        name: "San Diego St",
        homeAway: "home",
        order: 1,
        score: "63",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "COFC",
        alternateColor: "9e8959",
        color: "7a2531",
        id: "232",
        location: "Charleston",
        name: "Charleston",
        homeAway: "away",
        order: 2,
        score: "57",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/232.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/232.png",
        seed: "12",
      },
      date: "2023-03-16T19:25:00Z",
      id: "401522131",
      link: "/mens-college-basketball/game/_/gameId/401522131/charleston-san-diego-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 3,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "UVA",
        alternateColor: "f84c1e",
        color: "232d4b",
        id: "258",
        location: "Virginia",
        name: "Virginia",
        homeAway: "home",
        order: 1,
        score: "67",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/258.png",
        seed: "4",
      },
      competitorTwo: {
        abbreviation: "FUR",
        alternateColor: "ffffff",
        color: "582c83",
        id: "231",
        location: "Furman",
        name: "Furman",
        homeAway: "away",
        order: 2,
        score: "68",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/231.png",
        seed: "13",
      },
      date: "2023-03-16T16:40:00Z",
      id: "401522130",
      link: "/mens-college-basketball/game/_/gameId/401522130/furman-virginia",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 4,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "CREI",
        alternateColor: "6cadde",
        color: "005ca9",
        id: "156",
        location: "Creighton",
        name: "Creighton",
        homeAway: "home",
        order: 1,
        score: "72",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/156.png",
        seed: "6",
      },
      competitorTwo: {
        abbreviation: "NCSU",
        alternateColor: "ffffff",
        color: "cc0000",
        id: "152",
        location: "NC State",
        name: "NC State",
        homeAway: "away",
        order: 2,
        score: "63",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/152.png",
        seed: "11",
      },
      date: "2023-03-17T19:56:00Z",
      id: "401522152",
      link: "/mens-college-basketball/game/_/gameId/401522152/nc-state-creighton",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 5,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "BAY",
        alternateColor: "ffb81c",
        color: "154734",
        id: "239",
        location: "Baylor",
        name: "Baylor",
        homeAway: "home",
        order: 1,
        score: "74",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/239.png",
        seed: "3",
      },
      competitorTwo: {
        abbreviation: "UCSB",
        alternateColor: "febc11",
        color: "1e1840",
        id: "2540",
        location: "UC Santa Barbara",
        name: "Santa Barbara",
        homeAway: "away",
        order: 2,
        score: "56",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2540.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2540.png",
        seed: "14",
      },
      date: "2023-03-17T17:30:00Z",
      id: "401522151",
      link: "/mens-college-basketball/game/_/gameId/401522151/santa-barbara-baylor",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 6,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "MIZ",
        alternateColor: "000000",
        color: "f1b82d",
        id: "142",
        location: "Missouri",
        name: "Missouri",
        homeAway: "home",
        order: 1,
        score: "76",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/142.png",
        seed: "7",
      },
      competitorTwo: {
        abbreviation: "USU",
        alternateColor: "949ca1",
        color: "00263a",
        id: "328",
        location: "Utah State",
        name: "Utah State",
        homeAway: "away",
        order: 2,
        score: "65",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/328.png",
        seed: "10",
      },
      date: "2023-03-16T17:40:00Z",
      id: "401522135",
      link: "/mens-college-basketball/game/_/gameId/401522135/utah-state-missouri",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 7,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "ARIZ",
        alternateColor: "ab0520",
        color: "0c234b",
        id: "12",
        location: "Arizona",
        name: "Arizona",
        homeAway: "home",
        order: 1,
        score: "55",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/12.png",
        seed: "2",
      },
      competitorTwo: {
        abbreviation: "PRIN",
        alternateColor: "ff6000",
        color: "000000",
        id: "163",
        location: "Princeton",
        name: "Princeton",
        homeAway: "away",
        order: 2,
        score: "59",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/163.png",
        seed: "15",
      },
      date: "2023-03-16T20:10:00Z",
      id: "401522134",
      link: "/mens-college-basketball/game/_/gameId/401522134/princeton-arizona",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 8,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "PUR",
        alternateColor: "cfb991",
        color: "000000",
        id: "2509",
        location: "Purdue",
        name: "Purdue",
        homeAway: "home",
        order: 1,
        score: "58",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2509.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "FDU",
        alternateColor: "28334a",
        color: "72293c",
        id: "161",
        location: "Fairleigh Dickinson",
        name: "Fair Dickinson",
        homeAway: "away",
        order: 2,
        score: "63",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/161.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/161.png",
        seed: "16",
      },
      date: "2023-03-17T22:50:00Z",
      id: "401522145",
      link: "/mens-college-basketball/game/_/gameId/401522145/fair-dickinson-purdue",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 9,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "MEM",
        alternateColor: "8e908f",
        color: "004991",
        id: "235",
        location: "Memphis",
        name: "Memphis",
        homeAway: "home",
        order: 1,
        score: "65",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/235.png",
        seed: "8",
      },
      competitorTwo: {
        abbreviation: "FAU",
        alternateColor: "d31245",
        color: "00447c",
        id: "2226",
        location: "Florida Atlantic",
        name: "FAU",
        homeAway: "away",
        order: 2,
        score: "66",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2226.png",
        seed: "9",
      },
      date: "2023-03-18T01:44:00Z",
      id: "401522144",
      link: "/mens-college-basketball/game/_/gameId/401522144/fau-memphis",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 10,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "DUKE",
        alternateColor: "ffffff",
        color: "013088",
        id: "150",
        location: "Duke",
        name: "Duke",
        homeAway: "home",
        order: 1,
        score: "74",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/150.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "ORU",
        alternateColor: "dac792",
        color: "002462",
        id: "198",
        location: "Oral Roberts",
        name: "Oral Roberts",
        homeAway: "away",
        order: 2,
        score: "51",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/198.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/198.png",
        seed: "12",
      },
      date: "2023-03-16T23:10:00Z",
      id: "401522128",
      link: "/mens-college-basketball/game/_/gameId/401522128/oral-roberts-duke",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 11,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "TENN",
        alternateColor: "58595b",
        color: "ff8200",
        id: "2633",
        location: "Tennessee",
        name: "Tennessee",
        homeAway: "home",
        order: 1,
        score: "58",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2633.png",
        seed: "4",
      },
      competitorTwo: {
        abbreviation: "UL",
        alternateColor: "ffffff",
        color: "ce181e",
        id: "309",
        location: "Louisiana",
        name: "Louisiana",
        homeAway: "away",
        order: 2,
        score: "55",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/309.png",
        seed: "13",
      },
      date: "2023-03-17T01:40:00Z",
      id: "401522129",
      link: "/mens-college-basketball/game/_/gameId/401522129/louisiana-tennessee",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 12,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "UK",
        alternateColor: "ffffff",
        color: "0033a0",
        id: "96",
        location: "Kentucky",
        name: "Kentucky",
        homeAway: "home",
        order: 1,
        score: "61",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/96.png",
        seed: "6",
      },
      competitorTwo: {
        abbreviation: "PROV",
        alternateColor: "a3a19e",
        color: "000000",
        id: "2507",
        location: "Providence",
        name: "Providence",
        homeAway: "away",
        order: 2,
        score: "53",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2507.png",
        seed: "11",
      },
      date: "2023-03-17T23:10:00Z",
      id: "401522154",
      link: "/mens-college-basketball/game/_/gameId/401522154/providence-kentucky",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 13,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "KSU",
        alternateColor: "e2e3e4",
        color: "3c0969",
        id: "2306",
        location: "Kansas State",
        name: "Kansas St",
        homeAway: "home",
        order: 1,
        score: "77",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png",
        seed: "3",
      },
      competitorTwo: {
        abbreviation: "MTST",
        alternateColor: "bc955c",
        color: "00205c",
        id: "147",
        location: "Montana State",
        name: "Montana St",
        homeAway: "away",
        order: 2,
        score: "65",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/147.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/147.png",
        seed: "14",
      },
      date: "2023-03-18T01:55:00Z",
      id: "401522153",
      link: "/mens-college-basketball/game/_/gameId/401522153/montana-st-kansas-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 14,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "MSU",
        alternateColor: "ffffff",
        color: "18453b",
        id: "127",
        location: "Michigan State",
        name: "Michigan St",
        homeAway: "home",
        order: 1,
        score: "72",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/127.png",
        seed: "7",
      },
      competitorTwo: {
        abbreviation: "USC",
        alternateColor: "ffcc00",
        color: "9e2237",
        id: "30",
        location: "USC",
        name: "USC",
        homeAway: "away",
        order: 2,
        score: "62",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/30.png",
        seed: "10",
      },
      date: "2023-03-17T16:15:00Z",
      id: "401522142",
      link: "/mens-college-basketball/game/_/gameId/401522142/usc-michigan-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 15,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "MARQ",
        alternateColor: "ffcc00",
        color: "003366",
        id: "269",
        location: "Marquette",
        name: "Marquette",
        homeAway: "home",
        order: 1,
        score: "78",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/269.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/269.png",
        seed: "2",
      },
      competitorTwo: {
        abbreviation: "UVM",
        alternateColor: "ffc72c",
        color: "154734",
        id: "261",
        location: "Vermont",
        name: "Vermont",
        homeAway: "away",
        order: 2,
        score: "61",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/261.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/261.png",
        seed: "15",
      },
      date: "2023-03-17T18:51:00Z",
      id: "401522141",
      link: "/mens-college-basketball/game/_/gameId/401522141/vermont-marquette",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 16,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "HOU",
        alternateColor: "ffffff",
        color: "c92a39",
        id: "248",
        location: "Houston",
        name: "Houston",
        homeAway: "home",
        order: 1,
        score: "63",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/248.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "NKU",
        alternateColor: "000000",
        color: "ffc82e",
        id: "94",
        location: "Northern Kentucky",
        name: "N Kentucky",
        homeAway: "away",
        order: 2,
        score: "52",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/94.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/94.png",
        seed: "16",
      },
      date: "2023-03-17T01:39:00Z",
      id: "401522121",
      link: "/mens-college-basketball/game/_/gameId/401522121/n-kentucky-houston",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 17,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "IOWA",
        alternateColor: "fcd116",
        color: "000000",
        id: "2294",
        location: "Iowa",
        name: "Iowa",
        homeAway: "home",
        order: 1,
        score: "75",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2294.png",
        seed: "8",
      },
      competitorTwo: {
        abbreviation: "AUB",
        alternateColor: "f26522",
        color: "002b5c",
        id: "2",
        location: "Auburn",
        name: "Auburn",
        homeAway: "away",
        order: 2,
        score: "83",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2.png",
        seed: "9",
      },
      date: "2023-03-16T22:50:00Z",
      id: "401522120",
      link: "/mens-college-basketball/game/_/gameId/401522120/auburn-iowa",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 18,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "MIA",
        alternateColor: "f47321",
        color: "005030",
        id: "2390",
        location: "Miami",
        name: "Miami",
        homeAway: "home",
        order: 1,
        score: "63",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2390.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "DRKE",
        alternateColor: "bec0c2",
        color: "005596",
        id: "2181",
        location: "Drake",
        name: "Drake",
        homeAway: "away",
        order: 2,
        score: "56",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2181.png",
        seed: "12",
      },
      date: "2023-03-17T23:55:00Z",
      id: "401522139",
      link: "/mens-college-basketball/game/_/gameId/401522139/drake-miami",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 19,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "IU",
        alternateColor: "edebeb",
        color: "990000",
        id: "84",
        location: "Indiana",
        name: "Indiana",
        homeAway: "home",
        order: 1,
        score: "71",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/84.png",
        seed: "4",
      },
      competitorTwo: {
        abbreviation: "KENT",
        alternateColor: "efab00",
        color: "003976",
        id: "2309",
        location: "Kent State",
        name: "Kent State",
        homeAway: "away",
        order: 2,
        score: "60",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2309.png",
        seed: "13",
      },
      date: "2023-03-18T02:35:00Z",
      id: "401522138",
      link: "/mens-college-basketball/game/_/gameId/401522138/kent-state-indiana",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 20,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "ISU",
        alternateColor: "fdca2f",
        color: "822433",
        id: "66",
        location: "Iowa State",
        name: "Iowa State",
        homeAway: "home",
        order: 1,
        score: "41",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/66.png",
        seed: "6",
      },
      competitorTwo: {
        abbreviation: "PITT",
        alternateColor: "231f20",
        color: "003263",
        id: "221",
        location: "Pittsburgh",
        name: "Pitt",
        homeAway: "away",
        order: 2,
        score: "59",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/221.png",
        seed: "11",
      },
      date: "2023-03-17T19:30:00Z",
      id: "401522157",
      link: "/mens-college-basketball/game/_/gameId/401522157/pitt-iowa-state",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 21,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "XAV",
        alternateColor: "a5a7a8",
        color: "21304e",
        id: "2752",
        location: "Xavier",
        name: "Xavier",
        homeAway: "home",
        order: 1,
        score: "72",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2752.png",
        seed: "3",
      },
      competitorTwo: {
        abbreviation: "KENN",
        alternateColor: "000000",
        color: "fdbb30",
        id: "338",
        location: "Kennesaw State",
        name: "Kennesaw St",
        homeAway: "away",
        order: 2,
        score: "67",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/338.png",
        seed: "14",
      },
      date: "2023-03-17T16:40:00Z",
      id: "401522156",
      link: "/mens-college-basketball/game/_/gameId/401522156/kennesaw-st-xavier",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 22,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "TA&M",
        alternateColor: "ffffff",
        color: "500000",
        id: "245",
        location: "Texas A&M",
        name: "Texas A&M",
        homeAway: "home",
        order: 1,
        score: "59",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/245.png",
        seed: "7",
      },
      competitorTwo: {
        abbreviation: "PSU",
        alternateColor: "002e5c",
        color: "00265D",
        id: "213",
        location: "Penn State",
        name: "Penn State",
        homeAway: "away",
        order: 2,
        score: "76",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/213.png",
        seed: "10",
      },
      date: "2023-03-17T02:15:00Z",
      id: "401522127",
      link: "/mens-college-basketball/game/_/gameId/401522127/penn-state-texas-am",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 23,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "TEX",
        alternateColor: "ffffff",
        color: "c15d26",
        id: "251",
        location: "Texas",
        name: "Texas",
        homeAway: "home",
        order: 1,
        score: "81",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/251.png",
        seed: "2",
      },
      competitorTwo: {
        abbreviation: "COLG",
        alternateColor: "ffffff",
        color: "821019",
        id: "2142",
        location: "Colgate",
        name: "Colgate",
        homeAway: "away",
        order: 2,
        score: "61",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2142.png",
        seed: "15",
      },
      date: "2023-03-16T23:50:00Z",
      id: "401522124",
      link: "/mens-college-basketball/game/_/gameId/401522124/colgate-texas",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 24,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "KU",
        alternateColor: "e8000d",
        color: "0051ba",
        id: "2305",
        location: "Kansas",
        name: "Kansas",
        homeAway: "home",
        order: 1,
        score: "96",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2305.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "HOW",
        alternateColor: "e51937",
        color: "003a63",
        id: "47",
        location: "Howard",
        name: "Howard",
        homeAway: "away",
        order: 2,
        score: "68",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/47.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/47.png",
        seed: "16",
      },
      date: "2023-03-16T18:00:00Z",
      id: "401522125",
      link: "/mens-college-basketball/game/_/gameId/401522125/howard-kansas",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 25,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "ARK",
        alternateColor: "ffffff",
        color: "a41f35",
        id: "8",
        location: "Arkansas",
        name: "Arkansas",
        homeAway: "home",
        order: 1,
        score: "73",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/8.png",
        seed: "8",
      },
      competitorTwo: {
        abbreviation: "ILL",
        alternateColor: "13294b",
        color: "ff5f05",
        id: "356",
        location: "Illinois",
        name: "Illinois",
        homeAway: "away",
        order: 2,
        score: "63",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/356.png",
        seed: "9",
      },
      date: "2023-03-16T20:34:00Z",
      id: "401522126",
      link: "/mens-college-basketball/game/_/gameId/401522126/illinois-arkansas",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 26,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "SMC",
        alternateColor: "003057",
        color: "d80024",
        id: "2608",
        location: "Saint Mary's",
        name: "Saint Mary's",
        homeAway: "home",
        order: 1,
        score: "63",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2608.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "VCU",
        alternateColor: "000000",
        color: "ffaf00",
        id: "2670",
        location: "VCU",
        name: "VCU",
        homeAway: "away",
        order: 2,
        score: "51",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2670.png",
        seed: "12",
      },
      date: "2023-03-17T18:00:00Z",
      id: "401522137",
      link: "/mens-college-basketball/game/_/gameId/401522137/vcu-saint-marys",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 27,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "CONN",
        alternateColor: "f1f2f3",
        color: "0c2340",
        id: "41",
        location: "UConn",
        name: "UConn",
        homeAway: "home",
        order: 1,
        score: "87",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png",
        seed: "4",
      },
      competitorTwo: {
        abbreviation: "IONA",
        alternateColor: "f0ab00",
        color: "6f2c3e",
        id: "314",
        location: "Iona",
        name: "Iona",
        homeAway: "away",
        order: 2,
        score: "63",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/314.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/314.png",
        seed: "13",
      },
      date: "2023-03-17T20:45:00Z",
      id: "401522136",
      link: "/mens-college-basketball/game/_/gameId/401522136/iona-uconn",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 28,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "TCU",
        alternateColor: "f1f2f3",
        color: "4d1979",
        id: "2628",
        location: "TCU",
        name: "TCU",
        homeAway: "home",
        order: 1,
        score: "72",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2628.png",
        seed: "6",
      },
      competitorTwo: {
        abbreviation: "ASU",
        alternateColor: "ffc72c",
        color: "8e0c3a",
        id: "9",
        location: "Arizona State",
        name: "Arizona St",
        homeAway: "away",
        order: 2,
        score: "70",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/9.png",
        seed: "11",
      },
      date: "2023-03-18T02:05:00Z",
      id: "401522149",
      link: "/mens-college-basketball/game/_/gameId/401522149/arizona-st-tcu",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 29,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "GONZ",
        alternateColor: "c8102e",
        color: "041e42",
        id: "2250",
        location: "Gonzaga",
        name: "Gonzaga",
        homeAway: "home",
        order: 1,
        score: "82",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2250.png",
        seed: "3",
      },
      competitorTwo: {
        abbreviation: "GCU",
        alternateColor: "ffffff",
        color: "522398",
        id: "2253",
        location: "Grand Canyon",
        name: "Grand Canyon",
        homeAway: "away",
        order: 2,
        score: "70",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2253.png",
        seed: "14",
      },
      date: "2023-03-17T23:35:00Z",
      id: "401522148",
      link: "/mens-college-basketball/game/_/gameId/401522148/grand-canyon-gonzaga",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 30,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "NU",
        alternateColor: "ffffff",
        color: "582c83",
        id: "77",
        location: "Northwestern",
        name: "Northwestern",
        homeAway: "home",
        order: 1,
        score: "75",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/77.png",
        seed: "7",
      },
      competitorTwo: {
        abbreviation: "BOIS",
        alternateColor: "fa4616",
        color: "0033a0",
        id: "68",
        location: "Boise State",
        name: "Boise St",
        homeAway: "away",
        order: 2,
        score: "67",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/68.png",
        seed: "10",
      },
      date: "2023-03-16T23:35:00Z",
      id: "401522133",
      link: "/mens-college-basketball/game/_/gameId/401522133/boise-st-northwestern",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 31,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "UCLA",
        alternateColor: "f2a900",
        color: "2774ae",
        id: "26",
        location: "UCLA",
        name: "UCLA",
        homeAway: "home",
        order: 1,
        score: "86",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/26.png",
        seed: "2",
      },
      competitorTwo: {
        abbreviation: "UNCA",
        alternateColor: "ffffff",
        color: "003da5",
        id: "2427",
        location: "UNC Asheville",
        name: "UNC Asheville",
        homeAway: "away",
        order: 2,
        score: "53",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2427.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2427.png",
        seed: "15",
      },
      date: "2023-03-17T02:11:00Z",
      id: "401522132",
      link: "/mens-college-basketball/game/_/gameId/401522132/unc-asheville-ucla",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 32,
      roundId: 1,
    },
    {
      competitorOne: {
        abbreviation: "ALA",
        alternateColor: "ffffff",
        color: "9e1632",
        id: "333",
        location: "Alabama",
        name: "Alabama",
        homeAway: "home",
        order: 1,
        score: "73",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/333.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "MD",
        alternateColor: "ffcd00",
        color: "D5002B",
        id: "120",
        location: "Maryland",
        name: "Maryland",
        homeAway: "away",
        order: 2,
        score: "51",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/120.png",
        seed: "8",
      },
      date: "2023-03-19T02:02:00Z",
      id: "401522159",
      link: "/mens-college-basketball/game/_/gameId/401522159/maryland-alabama",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 1,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "SDSU",
        alternateColor: "000000",
        color: "c41230",
        id: "21",
        location: "San Diego State",
        name: "San Diego St",
        homeAway: "home",
        order: 1,
        score: "75",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "FUR",
        alternateColor: "ffffff",
        color: "582c83",
        id: "231",
        location: "Furman",
        name: "Furman",
        homeAway: "away",
        order: 2,
        score: "52",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/231.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/231.png",
        seed: "13",
      },
      date: "2023-03-18T16:10:00Z",
      id: "401522167",
      link: "/mens-college-basketball/game/_/gameId/401522167/furman-san-diego-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 2,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "CREI",
        alternateColor: "6cadde",
        color: "005ca9",
        id: "156",
        location: "Creighton",
        name: "Creighton",
        homeAway: "away",
        order: 1,
        score: "85",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/156.png",
        seed: "6",
      },
      competitorTwo: {
        abbreviation: "BAY",
        alternateColor: "ffb81c",
        color: "154734",
        id: "239",
        location: "Baylor",
        name: "Baylor",
        homeAway: "home",
        order: 2,
        score: "76",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/239.png",
        seed: "3",
      },
      date: "2023-03-19T23:10:00Z",
      id: "401522179",
      link: "/mens-college-basketball/game/_/gameId/401522179/creighton-baylor",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 3,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "MIZ",
        alternateColor: "000000",
        color: "f1b82d",
        id: "142",
        location: "Missouri",
        name: "Missouri",
        homeAway: "home",
        order: 1,
        score: "63",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/142.png",
        seed: "7",
      },
      competitorTwo: {
        abbreviation: "PRIN",
        alternateColor: "ff6000",
        color: "000000",
        id: "163",
        location: "Princeton",
        name: "Princeton",
        homeAway: "away",
        order: 2,
        score: "78",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/163.png",
        seed: "15",
      },
      date: "2023-03-18T22:10:00Z",
      id: "401522170",
      link: "/mens-college-basketball/game/_/gameId/401522170/princeton-missouri",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 4,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "FDU",
        alternateColor: "28334a",
        color: "72293c",
        id: "161",
        location: "Fairleigh Dickinson",
        name: "Fair Dickinson",
        homeAway: "away",
        order: 1,
        score: "70",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/161.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/161.png",
        seed: "16",
      },
      competitorTwo: {
        abbreviation: "FAU",
        alternateColor: "d31245",
        color: "00447c",
        id: "2226",
        location: "Florida Atlantic",
        name: "FAU",
        homeAway: "home",
        order: 2,
        score: "78",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2226.png",
        seed: "9",
      },
      date: "2023-03-20T00:06:00Z",
      id: "401522174",
      link: "/mens-college-basketball/game/_/gameId/401522174/fair-dickinson-fau",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "truTV",
      bracketLocation: 5,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "DUKE",
        alternateColor: "ffffff",
        color: "013088",
        id: "150",
        location: "Duke",
        name: "Duke",
        homeAway: "away",
        order: 1,
        score: "52",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/150.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "TENN",
        alternateColor: "58595b",
        color: "ff8200",
        id: "2633",
        location: "Tennessee",
        name: "Tennessee",
        homeAway: "home",
        order: 2,
        score: "65",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2633.png",
        seed: "4",
      },
      date: "2023-03-18T18:54:00Z",
      id: "401522166",
      link: "/mens-college-basketball/game/_/gameId/401522166/duke-tennessee",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 6,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "UK",
        alternateColor: "ffffff",
        color: "0033a0",
        id: "96",
        location: "Kentucky",
        name: "Kentucky",
        homeAway: "away",
        order: 1,
        score: "69",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/96.png",
        seed: "6",
      },
      competitorTwo: {
        abbreviation: "KSU",
        alternateColor: "e2e3e4",
        color: "3c0969",
        id: "2306",
        location: "Kansas State",
        name: "Kansas St",
        homeAway: "home",
        order: 2,
        score: "75",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png",
        seed: "3",
      },
      date: "2023-03-19T18:55:00Z",
      id: "401522180",
      link: "/mens-college-basketball/game/_/gameId/401522180/kentucky-kansas-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 7,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "MSU",
        alternateColor: "ffffff",
        color: "18453b",
        id: "127",
        location: "Michigan State",
        name: "Michigan St",
        homeAway: "away",
        order: 1,
        score: "69",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/127.png",
        seed: "7",
      },
      competitorTwo: {
        abbreviation: "MARQ",
        alternateColor: "ffcc00",
        color: "003366",
        id: "269",
        location: "Marquette",
        name: "Marquette",
        homeAway: "home",
        order: 2,
        score: "60",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/269.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/269.png",
        seed: "2",
      },
      date: "2023-03-19T21:15:00Z",
      id: "401522175",
      link: "/mens-college-basketball/game/_/gameId/401522175/michigan-st-marquette",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 8,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "HOU",
        alternateColor: "ffffff",
        color: "c92a39",
        id: "248",
        location: "Houston",
        name: "Houston",
        homeAway: "home",
        order: 1,
        score: "81",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/248.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "AUB",
        alternateColor: "f26522",
        color: "002b5c",
        id: "2",
        location: "Auburn",
        name: "Auburn",
        homeAway: "away",
        order: 2,
        score: "64",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2.png",
        seed: "9",
      },
      date: "2023-03-18T23:10:00Z",
      id: "401522161",
      link: "/mens-college-basketball/game/_/gameId/401522161/auburn-houston",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 9,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "MIA",
        alternateColor: "f47321",
        color: "005030",
        id: "2390",
        location: "Miami",
        name: "Miami",
        homeAway: "away",
        order: 1,
        score: "85",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2390.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "IU",
        alternateColor: "edebeb",
        color: "990000",
        id: "84",
        location: "Indiana",
        name: "Indiana",
        homeAway: "home",
        order: 2,
        score: "69",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/84.png",
        seed: "4",
      },
      date: "2023-03-20T00:40:00Z",
      id: "401522173",
      link: "/mens-college-basketball/game/_/gameId/401522173/miami-indiana",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 10,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "PITT",
        alternateColor: "231f20",
        color: "003263",
        id: "221",
        location: "Pittsburgh",
        name: "Pitt",
        homeAway: "away",
        order: 1,
        score: "73",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/221.png",
        seed: "11",
      },
      competitorTwo: {
        abbreviation: "XAV",
        alternateColor: "a5a7a8",
        color: "21304e",
        id: "2752",
        location: "Xavier",
        name: "Xavier",
        homeAway: "home",
        order: 2,
        score: "84",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2752.png",
        seed: "3",
      },
      date: "2023-03-19T16:10:00Z",
      id: "401522183",
      link: "/mens-college-basketball/game/_/gameId/401522183/pitt-xavier",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 11,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "PSU",
        alternateColor: "002e5c",
        color: "00265D",
        id: "213",
        location: "Penn State",
        name: "Penn State",
        homeAway: "away",
        order: 1,
        score: "66",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/213.png",
        seed: "10",
      },
      competitorTwo: {
        abbreviation: "TEX",
        alternateColor: "ffffff",
        color: "c15d26",
        id: "251",
        location: "Texas",
        name: "Texas",
        homeAway: "home",
        order: 2,
        score: "71",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/251.png",
        seed: "2",
      },
      date: "2023-03-19T00:17:00Z",
      id: "401522165",
      link: "/mens-college-basketball/game/_/gameId/401522165/penn-state-texas",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 12,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "KU",
        alternateColor: "e8000d",
        color: "0051ba",
        id: "2305",
        location: "Kansas",
        name: "Kansas",
        homeAway: "home",
        order: 1,
        score: "71",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2305.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "ARK",
        alternateColor: "ffffff",
        color: "a41f35",
        id: "8",
        location: "Arkansas",
        name: "Arkansas",
        homeAway: "away",
        order: 2,
        score: "72",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/8.png",
        seed: "8",
      },
      date: "2023-03-18T21:25:00Z",
      id: "401522162",
      link: "/mens-college-basketball/game/_/gameId/401522162/arkansas-kansas",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 13,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "SMC",
        alternateColor: "003057",
        color: "d80024",
        id: "2608",
        location: "Saint Mary's",
        name: "Saint Mary's",
        homeAway: "away",
        order: 1,
        score: "55",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2608.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "CONN",
        alternateColor: "f1f2f3",
        color: "0c2340",
        id: "41",
        location: "UConn",
        name: "UConn",
        homeAway: "home",
        order: 2,
        score: "70",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png",
        seed: "4",
      },
      date: "2023-03-19T22:10:00Z",
      id: "401522172",
      link: "/mens-college-basketball/game/_/gameId/401522172/saint-marys-uconn",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 14,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "TCU",
        alternateColor: "f1f2f3",
        color: "4d1979",
        id: "2628",
        location: "TCU",
        name: "TCU",
        homeAway: "away",
        order: 1,
        score: "81",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2628.png",
        seed: "6",
      },
      competitorTwo: {
        abbreviation: "GONZ",
        alternateColor: "c8102e",
        color: "041e42",
        id: "2250",
        location: "Gonzaga",
        name: "Gonzaga",
        homeAway: "home",
        order: 2,
        score: "84",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2250.png",
        seed: "3",
      },
      date: "2023-03-20T01:52:00Z",
      id: "401522178",
      link: "/mens-college-basketball/game/_/gameId/401522178/tcu-gonzaga",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 15,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "NU",
        alternateColor: "ffffff",
        color: "582c83",
        id: "77",
        location: "Northwestern",
        name: "Northwestern",
        homeAway: "away",
        order: 1,
        score: "63",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/77.png",
        seed: "7",
      },
      competitorTwo: {
        abbreviation: "UCLA",
        alternateColor: "f2a900",
        color: "2774ae",
        id: "26",
        location: "UCLA",
        name: "UCLA",
        homeAway: "home",
        order: 2,
        score: "68",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/26.png",
        seed: "2",
      },
      date: "2023-03-19T00:50:00Z",
      id: "401522169",
      link: "/mens-college-basketball/game/_/gameId/401522169/northwestern-ucla",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TNT",
      bracketLocation: 16,
      roundId: 2,
    },
    {
      competitorOne: {
        abbreviation: "ALA",
        alternateColor: "ffffff",
        color: "9e1632",
        id: "333",
        location: "Alabama",
        name: "Alabama",
        homeAway: "home",
        order: 1,
        score: "64",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/333.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "SDSU",
        alternateColor: "000000",
        color: "c41230",
        id: "21",
        location: "San Diego State",
        name: "San Diego St",
        homeAway: "away",
        order: 2,
        score: "71",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png",
        seed: "5",
      },
      date: "2023-03-24T22:30:00Z",
      id: "401522197",
      link: "/mens-college-basketball/game/_/gameId/401522197/san-diego-st-alabama",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 1,
      roundId: 3,
    },
    {
      competitorOne: {
        abbreviation: "CREI",
        alternateColor: "6cadde",
        color: "005ca9",
        id: "156",
        location: "Creighton",
        name: "Creighton",
        homeAway: "home",
        order: 1,
        score: "86",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/156.png",
        seed: "6",
      },
      competitorTwo: {
        abbreviation: "PRIN",
        alternateColor: "ff6000",
        color: "000000",
        id: "163",
        location: "Princeton",
        name: "Princeton",
        homeAway: "away",
        order: 2,
        score: "75",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/163.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/163.png",
        seed: "15",
      },
      date: "2023-03-25T01:27:00Z",
      id: "401522198",
      link: "/mens-college-basketball/game/_/gameId/401522198/princeton-creighton",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 2,
      roundId: 3,
    },
    {
      competitorOne: {
        abbreviation: "FAU",
        alternateColor: "d31245",
        color: "00447c",
        id: "2226",
        location: "Florida Atlantic",
        name: "FAU",
        homeAway: "away",
        order: 1,
        score: "62",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2226.png",
        seed: "9",
      },
      competitorTwo: {
        abbreviation: "TENN",
        alternateColor: "58595b",
        color: "ff8200",
        id: "2633",
        location: "Tennessee",
        name: "Tennessee",
        homeAway: "home",
        order: 2,
        score: "55",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2633.png",
        seed: "4",
      },
      date: "2023-03-24T01:36:00Z",
      id: "401522192",
      link: "/mens-college-basketball/game/_/gameId/401522192/fau-tennessee",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 3,
      roundId: 3,
    },
    {
      competitorOne: {
        abbreviation: "KSU",
        alternateColor: "e2e3e4",
        color: "3c0969",
        id: "2306",
        location: "Kansas State",
        name: "Kansas St",
        homeAway: "home",
        order: 1,
        score: "98",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png",
        seed: "3",
      },
      competitorTwo: {
        abbreviation: "MSU",
        alternateColor: "ffffff",
        color: "18453b",
        id: "127",
        location: "Michigan State",
        name: "Michigan St",
        homeAway: "away",
        order: 2,
        score: "93",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/127.png",
        seed: "7",
      },
      date: "2023-03-23T22:30:00Z",
      id: "401522191",
      link: "/mens-college-basketball/game/_/gameId/401522191/michigan-st-kansas-st",
      statusDesc: "Final",
      statusDetail: "Final/OT",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 4,
      roundId: 3,
    },
    {
      competitorOne: {
        abbreviation: "HOU",
        alternateColor: "ffffff",
        color: "c92a39",
        id: "248",
        location: "Houston",
        name: "Houston",
        homeAway: "home",
        order: 1,
        score: "75",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/248.png",
        seed: "1",
      },
      competitorTwo: {
        abbreviation: "MIA",
        alternateColor: "f47321",
        color: "005030",
        id: "2390",
        location: "Miami",
        name: "Miami",
        homeAway: "away",
        order: 2,
        score: "89",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2390.png",
        seed: "5",
      },
      date: "2023-03-24T23:15:00Z",
      id: "401522195",
      link: "/mens-college-basketball/game/_/gameId/401522195/miami-houston",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 5,
      roundId: 3,
    },
    {
      competitorOne: {
        abbreviation: "XAV",
        alternateColor: "a5a7a8",
        color: "21304e",
        id: "2752",
        location: "Xavier",
        name: "Xavier",
        homeAway: "away",
        order: 1,
        score: "71",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2752.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2752.png",
        seed: "3",
      },
      competitorTwo: {
        abbreviation: "TEX",
        alternateColor: "ffffff",
        color: "c15d26",
        id: "251",
        location: "Texas",
        name: "Texas",
        homeAway: "home",
        order: 2,
        score: "83",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/251.png",
        seed: "2",
      },
      date: "2023-03-25T01:59:00Z",
      id: "401522194",
      link: "/mens-college-basketball/game/_/gameId/401522194/xavier-texas",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 6,
      roundId: 3,
    },
    {
      competitorOne: {
        abbreviation: "ARK",
        alternateColor: "ffffff",
        color: "a41f35",
        id: "8",
        location: "Arkansas",
        name: "Arkansas",
        homeAway: "away",
        order: 1,
        score: "65",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/8.png",
        seed: "8",
      },
      competitorTwo: {
        abbreviation: "CONN",
        alternateColor: "f1f2f3",
        color: "0c2340",
        id: "41",
        location: "UConn",
        name: "UConn",
        homeAway: "home",
        order: 2,
        score: "88",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png",
        seed: "4",
      },
      date: "2023-03-23T23:15:00Z",
      id: "401522188",
      link: "/mens-college-basketball/game/_/gameId/401522188/arkansas-uconn",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 7,
      roundId: 3,
    },
    {
      competitorOne: {
        abbreviation: "GONZ",
        alternateColor: "c8102e",
        color: "041e42",
        id: "2250",
        location: "Gonzaga",
        name: "Gonzaga",
        homeAway: "away",
        order: 1,
        score: "79",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2250.png",
        seed: "3",
      },
      competitorTwo: {
        abbreviation: "UCLA",
        alternateColor: "f2a900",
        color: "2774ae",
        id: "26",
        location: "UCLA",
        name: "UCLA",
        homeAway: "home",
        order: 2,
        score: "76",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/26.png",
        seed: "2",
      },
      date: "2023-03-24T02:04:00Z",
      id: "401522186",
      link: "/mens-college-basketball/game/_/gameId/401522186/gonzaga-ucla",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 8,
      roundId: 3,
    },
    {
      competitorOne: {
        abbreviation: "SDSU",
        alternateColor: "000000",
        color: "c41230",
        id: "21",
        location: "San Diego State",
        name: "San Diego St",
        homeAway: "home",
        order: 1,
        score: "57",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "CREI",
        alternateColor: "6cadde",
        color: "005ca9",
        id: "156",
        location: "Creighton",
        name: "Creighton",
        homeAway: "away",
        order: 2,
        score: "56",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/156.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/156.png",
        seed: "6",
      },
      date: "2023-03-26T18:20:00Z",
      id: "401522199",
      link: "/mens-college-basketball/game/_/gameId/401522199/creighton-san-diego-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 1,
      roundId: 4,
    },
    {
      competitorOne: {
        abbreviation: "FAU",
        alternateColor: "d31245",
        color: "00447c",
        id: "2226",
        location: "Florida Atlantic",
        name: "FAU",
        homeAway: "away",
        order: 1,
        score: "79",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2226.png",
        seed: "9",
      },
      competitorTwo: {
        abbreviation: "KSU",
        alternateColor: "e2e3e4",
        color: "3c0969",
        id: "2306",
        location: "Kansas State",
        name: "Kansas St",
        homeAway: "home",
        order: 2,
        score: "76",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png",
        seed: "3",
      },
      date: "2023-03-25T22:09:00Z",
      id: "401522193",
      link: "/mens-college-basketball/game/_/gameId/401522193/fau-kansas-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 2,
      roundId: 4,
    },
    {
      competitorOne: {
        abbreviation: "MIA",
        alternateColor: "f47321",
        color: "005030",
        id: "2390",
        location: "Miami",
        name: "Miami",
        homeAway: "away",
        order: 1,
        score: "88",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2390.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "TEX",
        alternateColor: "ffffff",
        color: "c15d26",
        id: "251",
        location: "Texas",
        name: "Texas",
        homeAway: "home",
        order: 2,
        score: "81",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/251.png",
        seed: "2",
      },
      date: "2023-03-26T21:10:00Z",
      id: "401522196",
      link: "/mens-college-basketball/game/_/gameId/401522196/miami-texas",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 3,
      roundId: 4,
    },
    {
      competitorOne: {
        abbreviation: "CONN",
        alternateColor: "f1f2f3",
        color: "0c2340",
        id: "41",
        location: "UConn",
        name: "UConn",
        homeAway: "away",
        order: 1,
        score: "82",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png",
        seed: "4",
      },
      competitorTwo: {
        abbreviation: "GONZ",
        alternateColor: "c8102e",
        color: "041e42",
        id: "2250",
        location: "Gonzaga",
        name: "Gonzaga",
        homeAway: "home",
        order: 2,
        score: "54",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2250.png",
        seed: "3",
      },
      date: "2023-03-26T00:59:00Z",
      id: "401522190",
      link: "/mens-college-basketball/game/_/gameId/401522190/uconn-gonzaga",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "TBS",
      bracketLocation: 4,
      roundId: 4,
    },
    {
      competitorOne: {
        abbreviation: "SDSU",
        alternateColor: "000000",
        color: "c41230",
        id: "21",
        location: "San Diego State",
        name: "San Diego St",
        homeAway: "home",
        order: 1,
        score: "72",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "FAU",
        alternateColor: "d31245",
        color: "00447c",
        id: "2226",
        location: "Florida Atlantic",
        name: "FAU",
        homeAway: "away",
        order: 2,
        score: "71",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2226.png",
        seed: "9",
      },
      date: "2023-04-01T22:09:00Z",
      id: "401522200",
      link: "/mens-college-basketball/game/_/gameId/401522200/fau-san-diego-st",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 1,
      roundId: 5,
    },
    {
      competitorOne: {
        abbreviation: "MIA",
        alternateColor: "f47321",
        color: "005030",
        id: "2390",
        location: "Miami",
        name: "Miami",
        homeAway: "away",
        order: 1,
        score: "59",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2390.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "CONN",
        alternateColor: "f1f2f3",
        color: "0c2340",
        id: "41",
        location: "UConn",
        name: "UConn",
        homeAway: "home",
        order: 2,
        score: "72",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png",
        seed: "4",
      },
      date: "2023-04-02T01:16:00Z",
      id: "401522201",
      link: "/mens-college-basketball/game/_/gameId/401522201/miami-uconn",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 2,
      roundId: 5,
    },
    {
      competitorOne: {
        abbreviation: "SDSU",
        alternateColor: "000000",
        color: "c41230",
        id: "21",
        location: "San Diego State",
        name: "San Diego St",
        homeAway: "away",
        order: 1,
        score: "59",
        winner: false,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/21.png",
        seed: "5",
      },
      competitorTwo: {
        abbreviation: "CONN",
        alternateColor: "f1f2f3",
        color: "0c2340",
        id: "41",
        location: "UConn",
        name: "UConn",
        homeAway: "home",
        order: 2,
        score: "76",
        winner: true,
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
        logoDark: "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png",
        seed: "4",
      },
      date: "2023-04-04T01:20:00Z",
      id: "401522202",
      link: "/mens-college-basketball/game/_/gameId/401522202/san-diego-st-uconn",
      statusDesc: "Final",
      statusDetail: "Final",
      statusState: "post",
      timeValid: true,
      broadcasts: "CBS",
      bracketLocation: 1,
      roundId: 6,
    },
  ],
  name: "Men's NCAA Tournament",
  pageHeading: "Men's NCAA Tournament Bracket 2023 ",
  regions: [
    {
      id: 1,
      labelPrimary: "SOUTH",
      slug: "south",
    },
    {
      id: 2,
      labelPrimary: "EAST",
      slug: "east",
    },
    {
      id: 3,
      labelPrimary: "MIDWEST",
      slug: "midwest",
    },
    {
      id: 4,
      labelPrimary: "WEST",
      slug: "west",
    },
  ],
  rounds: [
    {
      id: 0,
      labelPrimary: "First Four",
      numMatchups: 4,
      start: "2023-03-14T22:40:00Z",
      end: "2023-03-15T22:40:00Z",
    },
    {
      id: 1,
      labelPrimary: "1st Round",
      numMatchups: 32,
      start: "2023-03-16T15:00:00Z",
      end: "2023-03-18T02:45:00Z",
    },
    {
      id: 2,
      labelPrimary: "2nd Round",
      numMatchups: 16,
      start: "2023-03-18T16:10:00Z",
      end: "2023-03-20T01:54:00Z",
    },
    {
      id: 3,
      labelPrimary: "Sweet 16",
      numMatchups: 8,
      start: "2023-03-23T23:09:00Z",
      end: "2023-03-25T02:20:00Z",
    },
    {
      id: 4,
      labelPrimary: "Elite 8",
      numMatchups: 4,
      start: "2023-03-25T22:09:00Z",
      end: "2023-03-26T21:05:00Z",
    },
    {
      id: 5,
      labelPrimary: "Final Four",
      numMatchups: 2,
      start: "2023-04-01T22:09:00Z",
      end: "2023-04-02T00:49:00Z",
    },
    {
      id: 6,
      labelPrimary: "Championship",
      numMatchups: 1,
      start: "2023-04-04T01:20:00Z",
      end: "2023-04-04T01:20:00Z",
    },
  ],
  season: "2023",
  seasonsFilter: {
    data: [
      {
        label: "2023-24",
        paramValue: "2024",
        value: "2024",
      },
      {
        label: "2022-23",
        paramValue: "2023",
        value: "2023",
      },
      {
        label: "2021-22",
        paramValue: "2022",
        value: "2022",
      },
      {
        label: "2020-21",
        paramValue: "2021",
        value: "2021",
      },
      {
        label: "2019-20",
        paramValue: "2020",
        value: "2020",
      },
      {
        label: "2018-19",
        paramValue: "2019",
        value: "2019",
      },
      {
        label: "2017-18",
        paramValue: "2018",
        value: "2018",
      },
      {
        label: "2016-17",
        paramValue: "2017",
        value: "2017",
      },
      {
        label: "2015-16",
        paramValue: "2016",
        value: "2016",
      },
      {
        label: "2014-15",
        paramValue: "2015",
        value: "2015",
      },
      {
        label: "2013-14",
        paramValue: "2014",
        value: "2014",
      },
      {
        label: "2012-13",
        paramValue: "2013",
        value: "2013",
      },
      {
        label: "2011-12",
        paramValue: "2012",
        value: "2012",
      },
      {
        label: "2010-11",
        paramValue: "2011",
        value: "2011",
      },
      {
        label: "2009-10",
        paramValue: "2010",
        value: "2010",
      },
      {
        label: "2008-09",
        paramValue: "2009",
        value: "2009",
      },
      {
        label: "2007-08",
        paramValue: "2008",
        value: "2008",
      },
      {
        label: "2006-07",
        paramValue: "2007",
        value: "2007",
      },
      {
        label: "2005-06",
        paramValue: "2006",
        value: "2006",
      },
      {
        label: "2004-05",
        paramValue: "2005",
        value: "2005",
      },
      {
        label: "2003-04",
        paramValue: "2004",
        value: "2004",
      },
      {
        label: "2002-03",
        paramValue: "2003",
        value: "2003",
      },
      {
        label: "2001-02",
        paramValue: "2002",
        value: "2002",
      },
      {
        label: "2000-01",
        paramValue: "2001",
        value: "2001",
      },
    ],
    defaultValue: "2023",
  },
  shortName: "NCAA",
  slug: "ncaa",
  edtrl: {
    logo: "https://a.espncdn.com/combiner/i?img=i/brackets/tournament/ncb-22-2023.png&w=280&h=280&scale=crop&cquality=80&location=center&format=png",
    pdf: "https://a.espncdn.com/i/ncaa/basketball/ncaatourney23/ncaam_bracket_filled.pdf",
    roundDates: {
      0: {
        start: "2023-03-14T22:40:00Z",
        end: "2023-03-15T22:40:00Z",
      },
      1: {
        start: "2023-03-16T15:00:00Z",
        end: "2023-03-18T02:45:00Z",
      },
      2: {
        start: "2023-03-18T16:10:00Z",
        end: "2023-03-20T01:54:00Z",
      },
      3: {
        start: "2023-03-23T23:09:00Z",
        end: "2023-03-25T02:20:00Z",
      },
      4: {
        start: "2023-03-25T22:09:00Z",
        end: "2023-03-26T21:05:00Z",
      },
      5: {
        start: "2023-04-01T22:09:00Z",
        end: "2023-04-02T00:49:00Z",
      },
      6: {
        start: "2023-04-04T01:20:00Z",
        end: "2023-04-04T01:20:00Z",
      },
    },
  },
  uiConfig: {
    22: {
      supportsPlayIn: true,
    },
    supportsPlayIn: true,
  },
};
